spring.application.name=SmartWeather

server.port=${SERVER_PORT:8080}

# Database Configuration (MySQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Validation
spring.jpa.properties.hibernate.validator.apply_to_ddl=false

# JSON Configuration
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# OpenWeatherMap API Configuration
openweather.api.key=${OPENWEATHER_API_KEY}
openweather.api.url=${OPENWEATHER_API_URL}
openuv.api.key=${OPENUV_API_KEY}
cors.allowed.origins=${CORS_ALLOWED_ORIGINS}

logging.level.org.springframework.boot.context.properties=DEBUG
logging.level.org.springframework.boot.diagnostics=DEBUG